apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
