apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-gateway.yaml
- frontend-virtualservice.yaml
- frontend-destinationrule.yaml
# - frontend-v2.yaml
- flagger-canary.yaml

# TODO patch is in main folder, think about it, maybe always use gateway and istio

# TODO delete frontend-external service

# TODO Describe in your report the methodology you use to check that the traffic is split correctly between v1 and v2
