apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-demo/kustomize/base
components:
# - monitoring

patches:
  - path: canary-version/frontend-v1.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
  - path: canary-version/frontend-external-svc-remove.yaml
    # target:
    #   # group: v1
    #   version: v1
    #   kind: Service
    #   name: frontend-external
