apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservices-demo/kustomize/base
- istio

patches:
  - path: istio/frontend-external-svc-remove.yaml
  - path: istio/loadgenerator-istio.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: loadgenerator


components:
  - monitoring
