{
 "title": "OBA Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_time_seconds - node_boot_time_seconds) by(node, job)"
    }
   ]
  },
  {
   "title": "CPU Usage overall (averaged)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage overall (averaged)",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) by(instance, job)) * 100"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "stat",
   "description": "Aggregated disk reads",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receives",
   "type": "stat",
   "description": "Aggregated network receiving rate",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[5m])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "stat",
   "description": "Aggregated disk writes",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmits",
   "type": "stat",
   "description": "Aggregated network transmitting rate",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[5m])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Node stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Node",
     "type": "timeseries",
     "description": "CPU Usage metric per node, averaged over cores",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage per Node (percentage)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)",
       "legendFormat": "Used {{instance}}"
      },
      {
       "expr": "avg(node_memory_MemAvailable_bytes) by (instance)",
       "legendFormat": "Available {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Space Used per Node",
     "type": "timeseries",
     "description": "Disk space used aggregated for each node",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100 - ((node_filesystem_avail_bytes{fstype!~\"root.*\",fstype!~\"tmp.*\",mountpoint!~\"/tmp.*\",mountpoint=~\"/|/data\"} / node_filesystem_size_bytes{fstype!~\"root.*\",fstype!~\"tmp.*\",mountpoint!~\"/tmp.*\",mountpoint=~\"/|/data\"}) * 100)) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk I/O per Node",
     "type": "timeseries",
     "description": "Aggregated disk I/O info per node (negative values for writes)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg(irate(node_disk_read_bytes_total[5m])*8) by (instance)",
       "legendFormat": "Reads {{instance}}"
      },
      {
       "expr": "-1 * avg(irate(node_disk_written_bytes_total[5m])*8) by (instance)",
       "legendFormat": "Writes {{instance}} "
      }
     ]
    },
    {
     "title": "Network Traffic per Node",
     "type": "timeseries",
     "description": "Aggregated network info per node (negative values for transmits)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(irate(node_network_receive_bytes_total[5m])*8) by (instance)",
       "legendFormat": "Recv {{instance}}"
      },
      {
       "expr": "-1 * avg(irate(node_network_transmit_bytes_total[5m])*8) by (instance)",
       "legendFormat": "Trans {{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Per Pod stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_user_seconds_total{container_label_io_kubernetes_container_name!=\"POD\",image!=\"\"}[5m]) * 100) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{image!=''}) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Space Usage per Pod",
     "type": "timeseries",
     "description": "Disk space used aggregated for each pod",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{image!=\"\",device!~\"/dev/dm.*\"}) by(container_label_io_kubernetes_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk I/O per Pod",
     "type": "timeseries",
     "description": "Aggregated disk I/O info per pod (negative values for writes)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{image!=\"\",device!~\"/dev/dm.*\"}[5m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "Writes {{container_label_io_kubernetes_pod_name}}"
      },
      {
       "expr": "-1 * sum(irate(container_fs_reads_bytes_total{image!=\"\",device!~\"/dev/dm.*\"}[5m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "Reads {{container_label_io_kubernetes_pod_name}} "
      }
     ]
    },
    {
     "title": "Network Traffic per Pod",
     "type": "timeseries",
     "description": "Aggregated network info per pod (negative values for transmits)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\"}[5m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "Recv {{container_label_io_kubernetes_pod_name}}"
      },
      {
       "expr": "-1 * sum(irate(container_network_receive_bytes_total{image!=\"\"}[5m])) by (container_label_io_kubernetes_pod_name)",
       "legendFormat": "Trans {{container_label_io_kubernetes_pod_name}} "
      }
     ]
    }
   ]
  },
  { "title": "Shop stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Placed Orders",
   "type": "stat",
   "description": "Shows the number of placed orders based on grpc OK responses for PlaceOrder function in checkoutservice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_server_handled_total{instance=~\"checkoutservice.*\",grpc_method=\"PlaceOrder\",grpc_code=\"OK\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most viewed products",
   "type": "bargauge",
   "description": "Shows the number of times a specific product has been visualized (retrieved from productcatalogservice), never retrieved products are not visualized",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(product_retrieval_count{job=\"productcatalogservice\"}) by(product_id, product_name))",
     "legendFormat": "{{product_name}} ({{product_id}})"
    }
   ]
  }
 ]
}