apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-node-pod
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  node-pod-monitoring.json: |
    {
      "dashboard": {
        // Paste your Grafana JSON here (shortened for brevity)
      }
    }