apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prometheus.yaml
- grafana.yaml
configMapGenerator:
- name: prometheus-config
  namespace: monitoring
  files:
  - prometheus-config.yml
- name: grafana-datasources
  namespace: monitoring
  files:
  - grafana-prometheus-datasource.yml
