apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prometheus.yaml
- grafana.yaml
configMapGenerator:
- name: prometheus-config
  namespace: monitoring
  files:
  - prometheus-config.yml
- name: grafana-datasources
  namespace: monitoring
  files:
  - grafana-prometheus-datasource.yml
- name: grafana-dashboards
  namespace: monitoring
  files:
  - grafana-dashboard-provider.yaml
  - grafana-dashboard.json
patches:
  - path: redis-exporter.patch.yaml
  - path: checkoutservice/checkoutservice-container.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: checkoutservice
  - path: checkoutservice/checkoutservice-service.patch.yaml
    target:
      version: v1
      kind: Service
      name: checkoutservice

# TODO remove disk space viz from dashboard because of stateless?
# TODO check why with some time spans, the graph is not displayed in Grafana
# TODO shipping service is the only one with otel stats export, but not implemented
# TODO ordini eseguiti: grpc_server_handled_total{instance=~"checkoutservice.*",grpc_method="PlaceOrder"}