apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prometheus.yaml
- grafana.yaml
configMapGenerator:
- name: prometheus-config
  namespace: monitoring
  files:
  - prometheus-config.yml
- name: grafana-datasources
  namespace: monitoring
  files:
  - grafana-prometheus-datasource.yml
- name: grafana-dashboards
  namespace: monitoring
  files:
  - grafana-dashboard-provider.yaml
  - grafana-dashboard.json
# TODO remove disk space viz from dashboard because of stateless?
# TODO check why with some time spans, the graph is not displayed in Grafana