apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prometheus.yaml
- prometheus-infrastructure-metrics.yaml
- grafana.yaml
configMapGenerator:
- name: prometheus-config
  namespace: monitoring
  files:
  - prometheus-config.yml
- name: grafana-datasources
  namespace: monitoring
  files:
  - grafana-prometheus-datasource.yml
- name: grafana-dashboards
  namespace: monitoring
  files:
  - grafana-dashboard-provider.yml
  - grafana-dashboard.json
- name: grafana-alerting
  namespace: monitoring
  files:
  - grafana-alerting.yml
patches:
  - path: redis-exporter.patch.yaml
  - path: checkoutservice/checkoutservice-container.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: checkoutservice
  - path: checkoutservice/checkoutservice-service.patch.yaml
    target:
      version: v1
      kind: Service
      name: checkoutservice
  - path: productcatalogservice/productcatalogservice-container.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: productcatalogservice
  - path: productcatalogservice/productcatalogservice-service.patch.yaml
    target:
      version: v1
      kind: Service
      name: productcatalogservice
