apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- prometheus.yaml
- grafana.yaml
# - grafana-config.yaml
configMapGenerator:
- name: prometheus-config
  namespace: monitoring
  files:
  - prometheus-config.yml