# This is the Prometheus configuration file. It is not a Kubernetes .yaml file.

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['prometheus.monitoring.svc.cluster.local:9090']
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor.monitoring.svc.cluster.local:8080']

# --------------------------------------------------------------

global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
# rule_files:
# - /etc/config/recording_rules.yml
# - /etc/config/alerting_rules.yml
# - /etc/config/rules
# - /etc/config/alerts
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: kubernetes-apiservers
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: default;kubernetes;https
  # - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
  #   action: keep
  #   regex: monitoring;kubernetes;https
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- job_name: kubernetes-nodes
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - source_labels: [__meta_kubernetes_node_name]
    target_label: __metrics_path__
    regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- job_name: kubernetes-nodes-cadvisor
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - source_labels: [__meta_kubernetes_node_name]
    target_label: __metrics_path__
    regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- job_name: kubernetes-service-endpoints
  honor_labels: true
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
    action: drop
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    target_label: __scheme__
    action: replace
    regex: (https?)
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    target_label: __metrics_path__
    action: replace
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    target_label: __address__
    action: replace
    regex: (.+?)(?::\d+)?;(\d+)
    replacement: $1:$2
  - action: labelmap
    regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
    replacement: __param_$1
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  # - source_labels: [__meta_kubernetes_namespace]
  #   target_label: namespace
  #   action: replace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: service
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    target_label: node
    action: replace
- job_name: kubernetes-service-endpoints-slow
  honor_labels: true
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    target_label: __scheme__
    action: replace
    regex: (https?)
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    target_label: __metrics_path__
    action: replace
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    target_label: __address__
    action: replace
    regex: (.+?)(?::\d+)?;(\d+)
    replacement: $1:$2
  - action: labelmap
    regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
    replacement: __param_$1
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: service
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    target_label: node
    action: replace
  scrape_interval: 5m
  scrape_timeout: 30s
- job_name: prometheus-pushgateway
  honor_labels: true
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    action: keep
    regex: pushgateway
- job_name: kubernetes-services
  honor_labels: true
  kubernetes_sd_configs:
  - role: service
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    action: keep
    regex: true
  - source_labels: [__address__]
    target_label: __param_target
  - replacement: blackbox
    target_label: __address__
  - source_labels: [__param_target]
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: service
- job_name: kubernetes-pods
  honor_labels: true
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
    action: drop
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    target_label: __scheme__
    action: replace
    regex: (https?)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    target_label: __metrics_path__
    action: replace
    regex: (.+)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
    target_label: __address__
    action: replace
    regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
    replacement: '[$2]:$1'
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
    target_label: __address__
    action: replace
    regex: (\d+);((([0-9]+?)(\.|$)){4})
    replacement: $2:$1
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
    replacement: __param_$1
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    action: drop
    regex: Pending|Succeeded|Failed|Completed
  - source_labels: [__meta_kubernetes_pod_node_name]
    target_label: node
    action: replace
- job_name: kubernetes-pods-slow
  honor_labels: true
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    target_label: __scheme__
    action: replace
    regex: (https?)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    target_label: __metrics_path__
    action: replace
    regex: (.+)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
    target_label: __address__
    action: replace
    regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
    replacement: '[$2]:$1'
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
    target_label: __address__
    action: replace
    regex: (\d+);((([0-9]+?)(\.|$)){4})
    replacement: $2:$1
  - action: labelmap
    regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
    replacement: __param_$1
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: namespace
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    action: drop
    regex: Pending|Succeeded|Failed|Completed
  - source_labels: [__meta_kubernetes_pod_node_name]
    target_label: node
    action: replace
  scrape_interval: 5m
  scrape_timeout: 30s

- job_name: redis_exporter
  static_configs:
  - targets: ['redis-exporter.default.svc.cluster.local:9121']

- job_name: grpc_checkoutservice
  static_configs:
  - targets: ['checkoutservice.default.svc.cluster.local:9090']

- job_name: productcatalogservice
  static_configs:
  - targets: ['productcatalogservice.default.svc.cluster.local:9090']


# alerting:
#   alertmanagers:
#   - kubernetes_sd_configs:
#       - role: pod
#     tls_config:
#       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_namespace]
#       regex: monitoring
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
#       regex: prometheus
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
#       regex: alertmanager
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_container_port_number]
#       regex: "9093"
#       action: keep

# TODO remove non needed jobs
# TODO test on gke with more than one node