- name: Deploy Docker Container
  hosts: all
  # become: true
  vars:
    docker_image_name: "us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator"
    docker_container_name: "my-loadgenerator"
    docker_image_tag: "v0.10.2"
  tasks:
    - name: Run Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        ports:
          - "8089:8089"
        env:
          FRONTEND_ADDR: "{{ frontend_external_ip }}"
          USERS: "10"
